services:

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend
    environment:
      BACKEND_DNS: "backend"

  backend:
    container_name: backend
    build: ./backend