apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
  type: ClusterIP
