apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - port: 5000
      protocol: TCP
      targetPort: 8080
  type: NodePort
