apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
  name: redis-service
spec:
  selector:
    app: redis
  ports:
    - port: 6379
      protocol: TCP
      targetPort: 6379
  type: ClusterIP