name: Deployment
on: push
#  pull_request:
#    types:
#      - closed
#    branches:
#      - 'main'
jobs:
  Deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Echoing Secret
        run: |
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > kubeconfig
          ls -a
      - name: Kubectl
        run: kubectl --kubeconfig kubeconfig apply -f ./deployment/
  
  Test:
    runs-on: ubuntu-latest
    needs: [Deployment]
    steps:
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Set up Kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > $HOME/.kube/config
      - name: Get Service Info
        run: |
          chmod +x ./get_service_info.sh
          ./get_service_info.sh

      - name: Testing
        run: |
          sleep 30
          wget http://$NODE_IP:NODE_PORT/