name: Deployment
on: push
#  pull_request:
#    types:
#      - closed
#    branches:
#      - 'main'
jobs:
  Deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Echoing Secret
        run: |
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > kubeconfig
          ls -a¨
          echo "Node IP: $(kubectl get nodes -o jsonpath='{.items[0].status.addresses[?(@.type=="ExternalIP")].address}')"
          echo "NodePort: $(kubectl get service my-service -o jsonpath='{.spec.ports[0].nodePort}')"
      - name: Kubectl
        run: kubectl --kubeconfig kubeconfig apply -f ./deployment/
  
  Test:
    runs-on: ubuntu-latest
    needs: [Deployment]
    steps:
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'
      
      - name: Set Up Kubeconfig for Test Job
        run: |
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > $HOME/.kube/config

      - name: Get Node External IP
        id: get_node_ip
        run: |
          NODE_IP=$(kubectl get nodes -o jsonpath='{.items[0].status.addresses[?(@.type=="ExternalIP")].address}')
          echo "NODE_IP=$NODE_IP" >> $GITHUB_ENV

      - name: Get NodePort
        id: get_nodeport
        run: |
          NODE_PORT=$(kubectl get service my-service -o jsonpath='{.spec.ports[0].nodePort}')
          echo "NODE_PORT=$NODE_PORT" >> $GITHUB_ENV

      - name: Testing
        run: |
          sleep 30
          wget http://${{ env.NODE_IP }}:${{ env.NODE_PORT }}/