name: Pipeline
on: push
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo down
        uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v4

      - name: Build Backend Application
        run: |
          cd backend
          go build
      
      - name: Build Frontend Application
        run: |
          cd frontend
          go build

      - name: Testing Backend
        run: |
          cd backend
          go test -v ./...  

      - name: Testing Frontend
        run: |
          cd frontend
          go test -v ./...
        