name: Pipeline
on: push
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo down
        uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v4

      - name: Build Backend Application
        run: go backend/build
      - name: Testing Backend
        run: go backend/test -v
      - name: Build Frontend Application
        run: go frontend/build
      - name: Testing Frontend
        run: go frontend/test -v
        