name: Pipeline
on: push
env:
  docker_username: vanden-dummy
  docker_passwork: ${{ secrets.GITHUB_TOKEN }}
  GIT_COMMIT: ${{ github.sha }}
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo down
        uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v4

      - name: Build Backend Application
        run: |
          cd backend
          go build
      
      - name: Build Frontend Application
        run: |
          cd frontend
          go build
      
      - name: Upload code
        uses: actions/upload-artifact@v4
        with:
          name: code
          path: .

  Testing:
    runs-on: ubuntu-latest
    needs: [Build]
    steps:
      - name: Clone Repo
        uses: actions/checkout@v4

      - name: Setup up Go
        uses: actions/setup-go@v4

      - name: Testing Frontend
        run: |
          cd frontend
          go test -v ./...
#        env:
#         DISABLE_ERRORS: true
  Docker-Backend:
    runs-on: ubuntu-latest
    needs: [Build]
    permissions:
      packages: write
    steps:
      - name: Download Code
        uses: actions/download-artifact@v4
        with:
          name: code
          path: .
      - name: Login to Github Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Backend Docker
        run: |
          cd backend
          docker build -t ghcr.io/vanden-dummy/devops-assignment/backend:latest -f Dockerfile .

      - name: Push Backend Image
        run: docker push ghcr.io/vanden-dummy/devops-assignment/backend:latest
    
  Docker-Frontend:
    runs-on: ubuntu-latest
    needs: [Build]
    permissions:
      packages: write
    steps:
      - name: Download Code
        uses: actions/download-artifact@v4
        with:
          name: code
          path: .
      - name: Login to Github Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Frontend Docker
        run: |
          cd frontend
          docker build -t ghcr.io/vanden-dummy/devops-assignment/frontend:latest -f Dockerfile .
      
      - name: Push Frontend Image
        run: docker push ghcr.io/vanden-dummy/devops-assignment/frontend:latest

        